### PR TITLE
Allow collapse/expand programatically via prop, keep global animation…

### LINKED ISSUE #61: Handle Read More/ Read Less from outside.
Is there any prop available to handle read more / read less from outside. like on button press or something.

### LINKED ISSUE #71: after using this library all my screen has animation
it's weird issue, after using this package in one of my screen then suddenly all my screen has animation.
example:
- smooth animation fade in and fade out transition
- in cart screen i have delete product function, when the product deleted from the state layout has bouncing animation transition.
- bouncing animation when user sliding up the bottom sheet

when i remove the import script of this package, all the animation is gone.

### PR DESCRIPTION
**Pull request by fawaz-ahmed**
… disbaled untill animate true/default is passed

### CODE REVIEW

**Comment by hotaryuzaki** [comment]
so the default value for setLayoutAnimationEnabledExperimental is false?
and we have to set animate props to true to change it?

if it so, i think you have to update the docs.
because it's stated for the animate props:
```defaults to true => applies a subtle animation to see more and see less text, not the complete text itself```

**Comment by fawaz-ahmed** [comment]
The logic is that, it will not set `setLayoutAnimationEnabledExperimental` if you pass `animate={false}`
However, if you dont pass animate prop, it will use default value which is true

**Comment by hotaryuzaki** [comment]
> The logic is that, it will not set `setLayoutAnimationEnabledExperimental` if you pass `animate={false}` However, if you dont pass animate prop, it will use default value which is true

oh okay, the default value for setLayoutAnimationEnabledExperimental is true.
so we have to set animate props to false to disable it, right?

**Comment by fawaz-ahmed** [comment]
> > The logic is that, it will not set `setLayoutAnimationEnabledExperimental` if you pass `animate={false}` However, if you dont pass animate prop, it will use default value which is true
> 
> oh okay, the default value for setLayoutAnimationEnabledExperimental is true. so we have to set animate props to false to disable it, right?

Yes that is correct

**Comment by hotaryuzaki** [comment]
> The logic is that, it will not set `setLayoutAnimationEnabledExperimental` if you pass `animate={false}` However, if you dont pass animate prop, it will use default value which is true

so this package still sets setLayoutAnimationEnabledExperimental to true by default?
it does not resolve my problem, because this package sets it for the entire app automatically.
I still need to patch this package to fix my issue.

My suggestion is to put setLayoutAnimationEnabledExperimental in the installation setup, so people have discretion to use it based on their needs.

**Comment by fawaz-ahmed** [comment]
If setting `animate={false}` by default, it will have 2 issues:
1. Break backward compatibility
2. It will be a choice by most of users to have animation enabled by default, since it will be desired in most cases.

Now, for the next part, which is setting `setLayoutAnimationEnabledExperimental`, it will be needed for animation. So by default it will be needed.

As per my update, if some user decides to not have animation enabled, then user can pass `animate={false}`.
It will disable animation and also not set `setLayoutAnimationEnabledExperimental`.

**Comment by hotaryuzaki** [comment]
You are right.
I found that native base also set setLayoutAnimationEnabledExperimental (true)
Maybe I have to fixed my issues in other way.
Thank you for your assistance.

**Comment by fawaz-ahmed** [comment]
> You are right. I found that native base also set setLayoutAnimationEnabledExperimental (true) Maybe I have to fixed my issues in other way. Thank you for your assistance.

You're welcome

**Pull request merged**
